### ISSUE TITLE
get the part from its property model does not work as we inject category=INSTANCE in the part retriever

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#119]
```
Out[2]: 
<pyke Property 'Werkvak' id 699a9b9f>
project.part(pk='87d64829-8534-4a05-bbc0-7f587626f3d3')
Traceback (most recent call last):
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0104b0b28d1c>", line 1, in <module>
    project.part(pk='87d64829-8534-4a05-bbc0-7f587626f3d3')
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\models\scope.py", line 33, in part
    return self._client.part(*args, bucket=self.bucket.get('id'), **kwargs)
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\client.py", line 345, in part
    raise NotFoundError("No part fits criteria")
pykechain.exceptions.NotFoundError: No part fits criteria
project.model(pk='87d64829-8534-4a05-bbc0-7f587626f3d3')
Out[4]: 
<pyke Part 'Keuringsformulier dwarsliggers' id 7626f3d3>
prop.part_id
Traceback (most recent call last):
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-0be2809e44f9>", line 1, in <module>
    prop.part_id
AttributeError: 'Property' object has no attribute 'part_id'
prop._json_data['part']
Out[6]: 
'87d64829-8534-4a05-bbc0-7f587626f3d3'
project.model(prop._json_data['part'])
Traceback (most recent call last):
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-c53c86791b85>", line 1, in <module>
    project.model(prop._json_data['part'])
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\models\scope.py", line 47, in model
    return self._client.model(*args, bucket=self.bucket.get('id'), **kwargs)
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\client.py", line 364, in model
    raise NotFoundError("No model fits criteria")
pykechain.exceptions.NotFoundError: No model fits criteria
project.model(pk=prop._json_data['part'])
Out[8]: 
<pyke Part 'Keuringsformulier dwarsliggers' id 7626f3d3>
project.part(model=project.model(pk=prop._json_data['part']))
Out[9]: 
<pyke Part 'Keuringsformulier dwarsliggers' id dd324f4d>

```

**Comment by jberends** [comment]
deployed 1.7.2
