### ISSUE TITLE
datetime is incorrectly recorded when providing tzinfo

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#121]
Thanks @joost.schut for reporting this

```
form_task.edit(due_date=datetime.datetime(2017,6,5, 5,0,0))

Traceback (most recent call last):
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-60-94037dfba8f6>", line 1, in <module>
    form_task.edit(due_date=datetime.datetime(2017,6,5, 5,0,0))
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\models\activity.py", line 121, in edit
    "This date is interpreted as UTC time.".format(start_date.isoformat(sep=' ')))
AttributeError: 'NoneType' object has no attribute 'isoformat'
```

and 

```
orm_task.edit(start_date=datetime.datetime(2017,6,7, 5,0,0))
C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\models\activity.py:111: UserWarning: The startdate '2017-06-07 05:00:00' is naive and not timezone aware, use tzinfo. This date is interpreted as UTC time.
  "This date is interpreted as UTC time.".format(start_date.isoformat(sep=' ')))
form_task.edit(start_date=datetime.datetime(2017,6,5, tzinfo=pytz.timezone('Europe/Amsterdam')))
form_task.edit(start_date=datetime.datetime(2017,6,5,0,0,0, tzinfo=pytz.timezone('Europe/Amsterdam')))
form_task.edit(due_date=datetime.datetime(2017,6,5,0,0,0, tzinfo=pytz.timezone('Europe/Amsterdam')))
form_task.edit(due_date=datetime.datetime(2017,6,5,0,0,0)))
  File "<ipython-input-70-aca48fc4cd5a>", line 1
    form_task.edit(due_date=datetime.datetime(2017,6,5,0,0,0)))
                                                              ^
SyntaxError: invalid syntax
form_task.edit(due_date=datetime.datetime(2017,6,5,0,0,0))
Traceback (most recent call last):
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-71-14185e8cc051>", line 1, in <module>
    form_task.edit(due_date=datetime.datetime(2017,6,5,0,0,0))
  File "C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\models\activity.py", line 121, in edit
    "This date is interpreted as UTC time.".format(start_date.isoformat(sep=' ')))
AttributeError: 'NoneType' object has no attribute 'isoformat'
form_task.edit(start_date=datetime.datetime(2017,6,5,0,0,0))
C:\Users\joost.schut\AppData\Local\Programs\Python\Python35\lib\site-packages\pykechain\models\activity.py:111: UserWarning: The startdate '2017-06-05 00:00:00' is naive and not timezone aware, use tzinfo. This date is interpreted as UTC time.
  "This date is interpreted as UTC time.".format(start_date.isoformat(sep=' ')))
form_task.edit(due_date=datetime.datetime(2017,6,5,5,0,0, tzinfo=pytz.timezone('Europe/Amsterdam')))
form_task.edit(due_date=datetime.datetime(2017,6,5,5,40,0, tzinfo=pytz.timezone('Europe/Amsterdam')))
form_task.edit(due_date=datetime.datetime(2017,6,5,5,20,0, tzinfo=pytz.timezone('Europe/Amsterdam')))

```

**Comment by jberends** [comment]
providing tzinfo inside the datetime object does not work for many tz's according to the pytzd documentation. do this:

```
        tz = pytz.timezone('Europe/Amsterdam')
        tzaware_due = tz.localize(datetime(2017, 7, 1))
        tzaware_start = tz.localize(datetime(2017, 6, 30, 0, 0, 0))
```

**Comment by jberends** [comment]
in version 1.7.3
