### ISSUE TITLE
Missing 'six' package

### ISSUE THREAD

**Issue by BennievanderWel** [KE-works/pykechain#152]
When retrieving a part (`kec.scope('Bike Project')`), I got the following error:

`Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from pykechain import Client
  File "/home/bennie/Development/docker-test/_venv/local/lib/python2.7/site-packages/pykechain/__init__.py", line 3, in <module>
    from .client import Client
  File "/home/bennie/Development/docker-test/_venv/local/lib/python2.7/site-packages/pykechain/client.py", line 9, in <module>
    from .models import Scope, Activity, Part, PartSet, Property
  File "/home/bennie/Development/docker-test/_venv/local/lib/python2.7/site-packages/pykechain/models/__init__.py", line 5, in <module>
    from .activity import Activity
  File "/home/bennie/Development/docker-test/_venv/local/lib/python2.7/site-packages/pykechain/models/activity.py", line 7, in <module>
    from six import text_type
ImportError: No module named six`

After installing six everything works as expected.

**Comment by jberends** [comment]
will be picked up in 1.10
