### ISSUE TITLE
Unknown API error on bulk widget creation

### ISSUE THREAD

**Issue by JelleBoersma** [KE-works/pykechain#625]
I have written a test for `client.create_widgets()`, see `test_widgets.test_create_widgets`.
It fails due to a KE-chain internal error that I cant resolve:

Traceback (most recent call last):
  File "/opt/ke-chain/pim3-test/_venv_py34/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ke-chain/pim3-test/_venv_py34/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/ke-chain/pim3-test/_venv_py34/lib/python3.5/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/ke-chain/pim3-test/_venv_py34/lib/python3.5/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/opt/ke-chain/pim3-test/_venv_py34/lib/python3.5/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/ke-chain/pim3-test/_venv_py34/lib/python3.5/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/ke-chain/pim3-test/kechain2/core/widget/api/widget/viewset.py", line 118, in bulk_create
    scope = activity.scope.get_keobject()
AttributeError: 'Scope' object has no attribute 'get_keobject'

**Comment by JelleBoersma** [comment]
@jberends This issue on `bulk_create` might be related to the `bulk_update` problem we just found.

**Comment by jberends** [comment]
I see, this is remnenescant of pim2 world - removed
