### ISSUE TITLE
Impediment retrieval of multi ref prop

### ISSUE THREAD

**Issue by jberends** [KE-works/pykechain#706]
```
pykechain! This will most likely break all projects!

  File "/usr/local/lib/python3.6/site-packages/pykechain/models/property2_multi_reference.py", line 77, in value
    self._cached_values = list(self._client.parts(id__in=','.join(ids), category=None))
  File "/usr/local/lib/python3.6/site-packages/pykechain/client.py", line 635, in parts
    raise NotFoundError("Could not retrieve parts: {}".format(response.content))
pykechain.exceptions.NotFoundError: Could not retrieve parts: b'{"msg": "Part API needs either scope_id, activity_id, \'widget_id\', parent_id, model_id or (part) id filter.", "detail": null, "traceback": "Traceback (most recent call last):\\n  File \\"/opt/ke-chain/demo-pim3/_venv/lib/python3.6/site-packages/django/core/handlers/base.py\\", line 185, in _get_response\\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\\n  File
```

**Comment by jberends** [comment]
@JelleBoersma we need to resolve this as soon as possible
